#!/usr/bin/env bash

set -euo pipefail

rm -f current.pdf debug.pdf tmp/current.tex tmp/debug.* tmp/test.ind

inputs=(metadata.md frontispiece.md intro.md foreword.md)

for section in CLARITY INFORMATION_THEORY ITILA SEWTHA DASHER PERSON; do
  inputs+=("intro_${section}.md")
  inputs+=("tmp/${section}.md")
done

inputs+=(last_word.md index.md back_cover.md)

pandoc "${inputs[@]}" -o mackay_tribute.pdf --pdf-engine=latexmk --pdf-engine-opt=-xelatex --include-in-header=header.tex --lua-filter=tribute.lua
cp mackay_tribute.pdf /mnt/c/Users/PilgrimBeart/Desktop
rm -f ./*.aux ./*.idx ./*.log ./*.out ./*.ilg ./*.ind ./*.xdv ./*.fdb_latexmk ./*.fls
